title: "Siyi Jiang（蒋思艺）"
author: "Siyi Jiang"
description: "Language & Cognition"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: false           #show site description and social links in the footer
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true              # use a dark header - ONLY applies if show_frame: false
show_description: true     # show the site description in the sidebar

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {file: "Research.md", title: "Research"}
  - {file: "Teaching.md", title: "Teaching"}
  - {file: "中文简历.pdf", title: "Chinese CV", url: "中文简历.pdf"}
  - {file: "英文简历.pdf", title: "English CV", url: "英文简历.pdf"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://grantmcdermott.com"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:gmcd@amazon.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/grant_mcdermott"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/grantmcdermott"
    - label: "Scholar"
      icon: "ai ai-google-scholar"
      url: "http://scholar.google.com/citations?user=EruWDMwAAAAJ"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "http://orcid.org/0000-0001-7883-8573"
      
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
